# Generated by Django 3.1.14 on 2023-02-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20221228_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='room',
            field=models.CharField(choices=[('온라인 강의실', '온라인 강의실'), ('학부모 회의실', '학부모 회의실'), ('스터디 카페', '스터디 카페')], max_length=20),
        ),
    ]
