# Generated by Django 3.2.17 on 2023-02-14 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0005_auto_20230213_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='number',
        ),
        migrations.AddField(
            model_name='teammember',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
