# Generated by Django 3.2.17 on 2023-04-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('novel', 'novel'), ('essey', 'essey')], default=None, max_length=30, null=True),
        ),
    ]
