# Generated by Django 3.2.17 on 2023-04-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='recommend',
            name='category',
            field=models.CharField(choices=[('novel', 'novel'), ('essey', 'essey')], default=None, max_length=30, null=True),
        ),
    ]
