# Generated by Django 3.2.17 on 2023-04-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20230425_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='category',
            field=models.CharField(choices=[('novel', 'novel'), ('essey', 'essay')], default=None, max_length=30, null=True),
        ),
    ]
