# Generated by Django 3.2.17 on 2023-06-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventimage_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
